COUNTY_URLS = {
    "ALACHUA": "https://www.alachua.realforeclose.com",
    "BAY": "https://bay.realforeclose.com",
    "BROWARD": "https://www.broward.realforeclose.com",
    "CHARLOTTE": "https://www.charlotte.realforeclose.com",
    "CITRUS": "https://www.citrus.realforeclose.com",
    "CLAY": "https://www.clay.realforeclose.com",
    "DUVAL": "https://www.duval.realforeclose.com",
    "ESCAMBIA": "https://escambia.realforeclose.com",
    "FLAGLER": "https://flagler.realforeclose.com",
    "GILCHRIST": "https://gilchrist.realforeclose.com",
    "GULF": "https://gulf.realforeclose.com",
    "HILLSBOROUGH": "https://www.hillsborough.realforeclose.com",
    "INDIAN RIVER": "https://indian-river.realforeclose.com",
    "JACKSON": "https://jackson.realforeclose.com",
    "LEE": "https://www.lee.realforeclose.com",
    "LEON": "https://www.leon.realforeclose.com",
    "MANATEE": "https://www.manatee.realforeclose.com",
    "MARION": "https://www.marion.realforeclose.com",
    "MARTIN": "https://www.martin.realforeclose.com",
    "MIAMI-DADE": "https://www.miamidade.realforeclose.com",
    "NASSAU": "https://nassauclerk.realforeclose.com",
    "OKEECHOBEE": "https://okeechobee.realforeclose.com/",
    "ORANGE": "https://www.myorangeclerk.realforeclose.com",
    "PALM BEACH": "https://palmbeach.realforeclose.com",
    "PASCO": "https://www.pasco.realforeclose.com",
    "PINELLAS": "https://www.pinellas.realforeclose.com",
    "POLK": "https://www.polk.realforeclose.com",
    "PUTNAM": "https://putnam.realforeclose.com",
    "SANTA ROSA": "https://santarosa.realforeclose.com",
    "SARASOTA": "https://sarasota.realforeclose.com",
    "SEMINOLE": "https://seminole.realforeclose.com",
    "ST. JOHNS": "https://www.saintjohns.realforeclose.com",
    "ST. LUCIE": "https://stlucie.realforeclose.com",
    "VOLUSIA": "https://www.volusia.realforeclose.com",
    "WALTON": "https://www.walton.realforeclose.com",
    "WASHINGTON": "https://washington.realforeclose.com",
}